version: '3.3'

volumes:
    postgres_data: {}

services:
  django:
    container_name: account-managment-django
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
      args:
          DJANGO_ENV: development
          WORKDIR: app
    depends_on:
      - postgres
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    restart: always
    env_file: .env

  postgres:
    container_name: account-managment-postgresql
    image: postgres:9.6
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - /var/run/postgresql:/var/run/postgresql
    env_file: .env

  mailhog:
    image: mailhog/mailhog:v1.0.0
    ports:
      - "8025:8025"

  vue:
    container_name: account-managment-vue-js
    build:
      context: .
      dockerfile: ./compose/vue/Dockerfile
    command: yarn run dev
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    env_file: .env
