# Generated by Django 2.0.4 on 2018-04-27 15:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(default='Current account', max_length=100, unique=True)),
                ('device', models.CharField(choices=[('mad', 'Dirham'), ('euro', 'Euro'), ('usd', 'Dollar')], max_length=100)),
                ('description', models.TextField(blank=True, default='Account to store all bank operations')),
                ('credit', models.IntegerField(default=0)),
                ('overdraft', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('categories', models.CharField(choices=[('deco', 'Decoration'), ('ameub', 'Ameublement'), ('sante', 'Santé'), ('course', 'Course'), ('vetm', 'Habillement'), ('assu', 'Assurances'), ('trans', 'Transports'), ('comm', 'Communications'), ('loisir', 'Loisirs'), ('etude', 'Etude'), ('garde', 'Garde'), ('restos', 'Restauration'), ('hotel', 'Hôtels'), ('services', 'Services'), ('culture', 'Culture'), ('diver', 'Divers')], max_length=100)),
                ('transaction', models.IntegerField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='api.Account')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='api.Bank'),
        ),
        migrations.AddField(
            model_name='account',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to=settings.AUTH_USER_MODEL),
        ),
    ]
